# Generated by Django 6.0.2 on 2026-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='librarian_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='librarian_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_librarian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
