services:
  db:
    image: postgres:16
    container_name: library_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

    networks:
      - library_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: library_backend

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    depends_on:
      db:
        condition: service_healthy

    networks:
      - library_network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: library_nginx

    depends_on:
      backend:
        condition: service_healthy

    volumes:
      - static_volume:/static:ro
      - media_volume:/media:ro

    networks:
      - library_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_dist:

networks:
  library_network:
    driver: bridge