# Generated by Django 6.0.2 on 2026-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
