# Generated by Django 6.0.2 on 2026-03-09 18:03

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploads.models.upload_to)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Завантаження',
                'verbose_name_plural': 'Завантаження',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='uploads_upl_name_66c972_idx')],
            },
        ),
    ]
