from django.db import models

class About(models.Model):
    institution_name = models.CharField(max_length=255)
    description = models.TextField()
    region = models.CharField(max_length=255)
    district = models.CharField(max_length=255)
    town = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=20)
    building_number = models.CharField(max_length=10)
    phone_number_1 = models.CharField(max_length=20)
    phone_number_2 = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField()
    librarian_first_name = models.CharField(max_length=255, blank=True, null=True)
    librarian_last_name = models.CharField(max_length=255, blank=True, null=True)
    about_librarian = models.TextField(blank=True, null=True)
    map = models.TextField(blank=True, null=True)
    librarian_photo = models.ForeignKey('uploads.Upload', on_delete=models.SET_NULL, null=True, blank=True, related_name='librarian_photos')
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    youtube = models.URLField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    working_hours = models.CharField(max_length=255, blank=True)