# Generated by Django 6.0.2 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_published_date_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(fields=('book', 'number'), name='unique_book_copy_number_per_book'),
        ),
    ]
