# Generated by Django 6.0.2 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Бібліотекар'), ('reader', 'Читач'), ('superuser', 'Адміністратор')], default='reader', max_length=20),
        ),
    ]
